# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4491b3aaf01ac021f0c76b552456b5cf38a87a08122a27d98d3668e54514a30526001a9ea34b3301c4c2c767326967e04c53201302d27d2f1e620460d2d8bab1

test:
  secret_key_base: 54054b4182deeba2275a15371d389a79de2494b2d028528a8caf489220d59ee2962542872e5e6e0df63f090d45ea674fff1a378b311415b6b8e45cc198e6c725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
